### ISSUE TITLE
saasus-theme ConfirmDialogで color と icon を 別々で指定できるようにする

### ISSUE THREAD

**Issue by yoritin** [Anti-Pattern-Inc/saasus-theme#69]
iconがwarningでcolorがredのパターンに対応する

![Image](https://user-images.githubusercontent.com/47884591/216775118-89f37877-775c-40e0-a0b8-f06a080c7f77.png)

**Comment by yutomoriyasu** [comment]
デザインチームと相談

**Comment by yutomoriyasu** [comment]
こちらに移動
- https://github.com/Anti-Pattern-Inc/saasus-front-monorepo/issues/61
