### ISSUE TITLE
MainTitleにパンくずオプション追加

### ISSUE THREAD

**Issue by BoxPistols** [Anti-Pattern-Inc/saasus-theme#72]
Figma
https://www.figma.com/file/uxyMcBE0zmQjvxidVD0s7P/%F0%9F%98%80SaaSus?node-id=6737%3A149998&t=3iTvtld2rGyxYnQN-0

**Comment by yutomoriyasu** [comment]
- こちらに移動 https://github.com/Anti-Pattern-Inc/saasus-front-monorepo/issues/74
