### ISSUE TITLE
ClipBoardのアップデート コンポーネント化

### ISSUE THREAD

**Issue by BoxPistols** [Anti-Pattern-Inc/saasus-theme#75]
ClipBoardのコンポーネント化
- 既存のClipBoardをコンポーネント化
- Option領域を右側に作成
- Helperテキストを右下に作成

未設置箇所への反映
- https://settings.console.dev.saasus.io/apikey

**Comment by BoxPistols** [comment]
![Image](https://github.com/Anti-Pattern-Inc/saasus-theme/assets/10333049/1fd87a69-15ec-433b-9f2b-d639f2d359a7)

**Comment by akira-yasuzawa** [comment]
クリップボードのコンポーネントは作成済みのためクローズ
