### ISSUE TITLE
ClipBoardコンポーネントデザイン展開

### ISSUE THREAD

**Issue by BoxPistols** [Anti-Pattern-Inc/saasus-theme#76]
単体だけでなく、複数ならぶパターンもあるため、コンポーネントの拡張

https://anti-patterninc.slack.com/archives/C02T9B3M656/p1686048439596049?thread_ts=1686045056.044929&cid=C02T9B3M656

**Comment by akira-yasuzawa** [comment]
クリップボードが複数並んだときのコンポーネントがない

**Comment by akira-yasuzawa** [comment]
必要になった際にコンポーネントを改めて作成する
